-- 코드를 입력하세요
SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM REST_INFO a, (
     SELECT FOOD_TYPE, MAX(FAVORITES) MF FROM REST_INFO GROUP BY 1) b
WHERE a.FOOD_TYPE = b.FOOD_TYPE AND a.FAVORITES = b.MF
ORDER BY 1 DESC