-- 코드를 입력하세요
SELECT a.YEAR, a.MONTH, a.COUNT PUCHASED_USERS, 
    ROUND((a.COUNT / b.TOTAL),1) PUCHASED_RATIO
FROM (
    SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
           COUNT(DISTINCT USER_ID) COUNT
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID
                      FROM USER_INFO
                      WHERE year(JOINED) = 2021)
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)) a, (
    SELECT COUNT(USER_ID) TOTAL
    FROM USER_INFO
    WHERE year(JOINED) = 2021) b
ORDER BY 1,2