-- 코드를 입력하세요
SELECT MEMBER_NAME, c.REVIEW_TEXT REVIEW_TEXT, 
    DATE_FORMAT(c.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE a, 
    (SELECT MEMBER_ID ID, COUNT(*) COT 
     FROM REST_REVIEW
     GROUP BY 1
     ORDER BY 2 DESC
     LIMIT 1) b, REST_REVIEW c
WHERE a.MEMBER_ID = b.ID AND b.ID = c.MEMBER_ID
ORDER BY 3,2;