-- 코드를 입력하세요
SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE,'%Y-%m-%d'), (
 CASE WHEN OUT_DATE IS NULL THEN '출고미정'
      WHEN DATEDIFF('2022-05-01',DATE_FORMAT(OUT_DATE,'%Y-%m-%d'))>=0 THEN '출고완료'
      WHEN DATEDIFF('2022-05-01',DATE_FORMAT(OUT_DATE,'%Y-%m-%d'))<0 THEN '출고대기'
           END) 출고여부
FROM FOOD_ORDER
ORDER BY 1
/*
SELECT DATEDIFF('2022-05-01',DATE_FORMAT(OUT_DATE,'%Y-%m-%d')), OUT_DATE
FROM FOOD_ORDER*/